#!/bin/sh
# Accept two flags -a and -n to delete all images or only the ones with the <none> tag

if [ "$1" = "-a" ]; then
    docker rmi -f $(docker images -q)
elif [ "$1" = "-n" ]; then
    docker rmi -f $(docker images | grep "^<none>" | awk '{print $3}')
else
    echo "Usage: doc_d {-a|-n}"
    echo "  -a: Remove all images"
    echo "  -n: Remove images with the <none> tag"
    exit 1
fi

