#!/bin/sh
#Pull latest of a remote branch to local.

if [ -z $1 ]
	then
		echo "Enter the name of the remote branch you want to pull. e.g. git_remote feature/zebit-some-branch";
	else
		git checkout main
		git fetch
		git checkout -b $1 origin/$1
fi
