#!/bin/bash
# Open app in a specific workspace

# Ensure wmctrl is installed
if ! command -v wmctrl &> /dev/null; then
    echo "wmctrl is not installed. Installing..."
    sudo apt update && sudo apt install -y wmctrl
fi

# Check for arguments
if [ $# -lt 1 ]; then
    echo "Opens a gui app in a specific workspace."
    echo "Example: oow 3 code ."
    exit 1
fi

# Calc workspace number (convert human-friendly 1-based index to 0-based).
if [[ $1 =~ ^[1-9]+$ ]]; then
    WORKSPACE=$(($1 - 1))
else
    WORKSPACE=0
fi

shift
wmctrl -s "$WORKSPACE"

# Run the command
if [ $# -gt 0 ]; then
    "$@"
fi
